server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/bancodigital2
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    url: jdbc:h2:~/bancodigital2
    user: root
    password: root
    enabled: true